version: "3"
networks:
  default:

services:
  postgres:
    container_name: popchef_postgres
    image:  nickblah/postgis:10.17-postgis-2.4.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=1684
#    volumes:
#      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  redis:
    image: bitnami/redis:latest
    container_name: popchef_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  pgadmin4:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-fake@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-postgres}
    ports:
      - "8889:80"

